@url = https://8080-marcoweb-gamessw22024a-g73mmwi4si9.ws-us116.gitpod.io

GET {{url}}/jogos

###
POST {{url}}/jogos
Content-Type: application/json

{
    "titulo": "Vampire Survivors",
    "plataformas": [
        {"id": 1},
        {"id": 2}
    ]
}