@url = https://8080-marcoweb-gamessw22024a-h2akrv9vn2d.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "PC"
}

###
GET {{url}}/plataformas/8