@url = https://8080-marcoweb-gamessw22024a-g73mmwi4si9.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "XBox"
}

###
GET {{url}}/plataformas/8